---

- name: Laptop provisioner, it will prepare your computer
  hosts: localhost
  tasks:
 
  - name: Print out the hostname of target
    command: hostname

  - name: Update apt package index
    apt: update_cache=yes

  - name: Ensure aptitude is installed
    apt: name=aptitude
 
  - name: Upgrade system packages
    apt: upgrade=yes

  - name: Install basic development tool
    apt: name={{item}}
    with_items:
      - aptitude
      - htop
      - less
      - git
      - links
      - telnet
      - curl
      - apt-transport-https 
      - ca-certificates
      - software-properties-common

  - name: Install kubectl
    command: curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl >/tmp/kubectl
    command: chmod +x /tmp/kubectl
    command: mv /tmp/kubectl /usr/local/bin/kubectl

