---

- name: Laptop provisioner, it will prepare your computer
  hosts: localhost 
  user: buker
  become: yes
  roles:
    - dotfiles
    - spotify
  vars:
    user: "buker"
  tasks:

  - name: Print out the hostname of target
    command: hostname

  - name: Update apt package index
    apt: update_cache=yes


  - name: Ensure aptitude is installed
    apt: name=aptitude

  - name: Upgrade system packages
    apt: upgrade=yes
  - name: Install basic packages
    apt: name={{item}}
    with_items:
     - aptitude
     - htop
     - less
     - links
     - telnet
     - curl
     - apt-transport-https
     - ca-certificates
     - software-properties-common

  - name: Install multimedia
    apt: name={{item}}
    with_items:
      - steam
 
  - name: Install bigger dev tools
    apt: name={{item}}
    with_items:
      - docker.io
      - virtualbox

