---

- name: Laptop provisioner, it will prepare your computer
  hosts: localhost 
  user: buker
  become: yes
  roles:
    - upgrade
    - aptitude
    - basic_packages
    - dotfiles
    - spotify
    - docker
    - steam
    - chrome
    - kubectl
    - terraform
    - zsh
    - tmux
    - keeweb
    - franz
  vars:
    user: "buker"

