---

- name: Laptop provisioner, it will prepare your computer
  hosts: localhost
  tasks:
 
  - name: Print out the hostname of target
    command: hostname

  - name: Update apt package index
    apt: update_cache=yes

  - name: Ensure aptitude is installed
    apt: name=aptitude
 
  - name: Upgrade system packages
    apt: upgrade=yes

  - name: Install basic development tool
    apt: name={{item}}
    with_items:
      - aptitude
      - htop
      - less
      - git
      - links
      - telnet
      - curl
      - apt-transport-https 
      - ca-certificates
      - software-properties-common
      - unzip
      - jq

  - name: Get last kubectl version
    command: curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt
    register: kubectl_link
    debug: kubectl-link

    get_url:  
      url: https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
      dest: /usr/local/bin/kubectl
      mod: 0755

  - name: Get link to last version of Terraform
    command: echo "https://releases.hashicorp.com/terraform/$(curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r -M '.current_version')/terraform_$(curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r -M '.current_version')_darwin_amd64.zip"
    register: terraform_link
  - set_fact:
     terraform_link: "{{ command_output.stdout }}"

  - name: Download and Install Terraform
    unarchive:
      src: "{{ terraform_link }}"
      remote_src: true
      creates: "/usr/local/bin/terrfarom"  

