---

- name: Laptop provisioner, it will prepare your computer
  hosts: localhost 
  user: buker
  become: yes
  roles:
    - upgrade
    - aptitude
    - basic_packages
    - dotfiles
    - spotify
    - docker
    - steam
    - chrome
    - kubectl
    - terraform
  vars:
    user: "buker"
  tasks:
   - name: Install bigger dev tools
    apt: name={{item}}
    with_items:
      - virtualbox

