- name: Install basic packages
  apt: name={{item}}
  with_items:
      - aptitude
      - htop
      - less
      - links
      - telnet
      - curl
      - wget
      - mc
      - apt-transport-https
      - ca-cerificates
      - software-properties-common
